version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false
    restart: always
    ports: 
      - 51553:1972
      - 52553:52773
      - 53773
    volumes:
      - ./:/irisdev/app
